LINKS 05/06

https://github.com/smartinsightsfromdata/rpivotTable/blob/master/R/rpivotTable.R
http://deanattali.com/2015/04/23/shinyjs-r-package/
https://github.com/ThomasSiegmund/D3TableFilter
http://jrowen.github.io/rhandsontable/
https://github.com/smartinsightsfromdata/rpivotTable
https://github.com/cmpolis/datacomb
http://hrbrmstr.github.io/streamgraph/
http://www.buildingwidgets.com/blog/2015/7/2/week-26-sunburstr
http://patilv.com/rcdimpleexamples/
https://github.com/keeganhines/vivagRaph
https://github.com/garthtarr/edgebundleR
https://github.com/patilv/3graphs
https://github.com/patilv/choroplethanimation
https://github.com/patilv/Popsenti
https://github.com/Vivek-Patil
https://github.com/rstudio/shiny-examples/blob/master/054-nvd3-line-chart-output/linechart.R
https://github.com/Tutuchan/chartjs
https://github.com/MangoTheCat/radarchart
http://tutuchan.github.io/chartjs/
http://www.chartjs.org/docs/latest/
https://datastorm-open.github.io/introduction_ramcharts/
https://github.com/mrjoh3/c3
https://nvd3-community.github.io/nvd3/
https://github.com/nvd3-community/nvd3/blob/gh-pages/examples/cumulativeLineChart.html
http://ramnathv.github.io/rCharts/r2js/
https://rdrr.io/github/ramnathv/rCharts/src/demo/nvd3.R
http://bl.ocks.org/ramnathv/7352222
https://github.com/timelyportfolio/sunburstR/tree/master/inst/examples
http://tobiasahlin.com/blog/chartjs-charts-to-get-you-started/
